feat: export csv or excel
nhn/tui.grid pull request #1465
Opened 2021-09-06 09:03 UTC by jajugoguma

### Please check if the PR fulfills these requirements
- [x] It's submitted to right branch according to our branching model
- [ ] It's right issue type on title
- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [x] The commit message follows our guidelines
- [x] Tests for the changes have been added (for bug fixes/features)
- [x] Docs have been added/updated (for bug fixes/features)
- [ ] It does not introduce a breaking change or has description for the breaking change

### Description

- Add csv or excel export feature and API.
- Export feature support complex columns, row headers, tree, frozen columns, sort, filter and etc.
  - In CSV export, it doesn't support complex columns and when it used, headers doesn't export.
- If use row header, it exports row numbers only.

**API**
 - `exportData(format: 'csv' | 'xlsx', exportOpt?: ExportOpt)`

**ContextMenu**
- Add context menu item 'export' and sub menu item 'CSV export' and 'Excel export' under it
<img width="435" alt="context menu for export" src="https://user-images.githubusercontent.com/41339744/132184356-3bde459b-ec08-4443-8cea-90d41d6604a7.png">

---
Thank you for your contribution to TOAST UI product. 🎉 😘 ✨

2021-09-09 01:56 UTC, lja1018 reviewed
리뷰완료합니다.

2021-09-09 01:56 UTC, lja1018 commented on packages/toast-ui.grid/cypress/integration/export.spec.ts
> +  return 'Excel';
```suggestion
  return format === 'csv' ? 'CSV' : 'Excel';
```
이렇게 줄이는건 어떤가요?
format이 `'csv'`랑 `'excel'`이라면 `toUpperCase`로 리턴해도 괜찮을 것 같아요.

2021-09-09 01:56 UTC, lja1018 commented on packages/toast-ui.grid/cypress/integration/export.spec.ts
> +    });
```suggestion
    callback = cy.stub().callsFake((ev: GridEvent) => ev.stop());
```
바로 리턴해도 될것 같아요.

2021-09-09 01:56 UTC, lja1018 commented on packages/toast-ui.grid/cypress/integration/export.spec.ts
> +      it(`should export data according to defulat export options to '${format}'`, () => {
`default` 오타네요

2021-09-09 01:56 UTC, lja1018 commented on packages/toast-ui.grid/cypress/integration/export.spec.ts
> +  return 'Excel';
아래를 보니 `'xlsx'`라서 `toUpperCase`는 안되겠네요.

2021-09-09 01:56 UTC, lja1018 commented on packages/toast-ui.grid/docs/ko/export.md
> +엑셀 내보내기는 복합 컬럼을 지원하지만 CSV 내보내지는 이를 지원하지 않는다. 만약 복합 컬럼을 사용하는 중에 CSV 내보내기를 수행하면 컬럼 헤더는 내보내지 않는다.
`CSV 내보내기는` 오타인 것 같습니다.

2021-09-09 01:56 UTC, lja1018 commented on packages/toast-ui.grid/src/dispatch/export.ts
> +  } else if (columnNames.length === 0) {
`!columnNames.length`는 어떤가요?

2021-09-09 01:56 UTC, lja1018 commented on packages/toast-ui.grid/src/dispatch/export.ts
> +        if (!(merge.s.r === merge.e.r && merge.s.c === merge.e.c)) {
개인적인 차이긴 한데 `merge.s.r !== merge.e.r || merge.s.c !== merge.e.c`는 어떤가요?

2021-09-09 01:56 UTC, lja1018 commented on packages/toast-ui.grid/cypress/integration/export.spec.ts
> +function formatToType(format: string) {
`format: 'csv' | 'xlsx'`로 해도 될 것 같습니다.

2021-09-09 01:56 UTC, lja1018 commented on packages/toast-ui.grid/src/dispatch/export.ts
> +    if (includeHeader && column.complexColumnHeaders.length === 0) {
`!column.complexColumnHeaders.length`는 어떤가요?

2021-09-09 01:56 UTC, lja1018 commented on packages/toast-ui.grid/src/dispatch/export.ts
> +  } else if (format === 'xlsx') {
`format`이 `'csv'` 아니면 `'xlsx'`라서 else만 써도 되지 않나요?

2021-09-09 05:28 UTC, js87zz commented on packages/toast-ui.grid/cypress/integration/export.spec.ts
> +function formatToType(format: string) {
이 함수는 테스트 코드에서 호출하기보다는 `getMenuItemByText` 안에서 처리해주는게 테스트 코드를 작성하거나 읽을때 더 낫겠네요~

2021-09-09 05:32 UTC, js87zz commented on packages/toast-ui.grid/cypress/integration/export.spec.ts
> +        getMenuItemByText(`${formatToType(format)} Export`).click();
`getMenuItemByText`를 좀 더 발전 시켜서 원하는 메뉴(csv, excel)를 찾아서 클릭하는 동작 자체를 함수로 만들어두는데 더 편하지 않을까요?

2021-09-09 05:33 UTC, js87zz commented on packages/toast-ui.grid/cypress/integration/export.spec.ts
> +    it(`should export data without column headers when with complex column headers to 'csv'`, () => {
여긴 그냥 따옴표로 해도 되겠네요ㅎㅎ

2021-09-09 05:37 UTC, js87zz commented on packages/toast-ui.grid/cypress/integration/export.spec.ts
> +  describe('Without column headers', () => {
테스트 설명에 옵션 명도 같이 써주면 파악하기 더 좋겠네요~! 개인적으로는 옵션 명만 있어도 테스트 읽는데 크게 문제가 없을 것 같네요

2021-09-09 05:46 UTC, js87zz commented on packages/toast-ui.grid/cypress/integration/export.spec.ts
> +      it(`should export data of selected range to '${format}' regardless of "includeHiddenColumns" and "columnNames" options`, () => {
가이드에 이런 옵션 우선 순위는 꼭 명시 부탁드려요~

2021-09-09 06:00 UTC, js87zz commented on packages/toast-ui.grid/cypress/integration/export.spec.ts
> +      });
이 테스트는 결국 `includeHiddenColumns`보다 `columnNames`가 우선시 되는걸 검증하는 것 같은데 여기서 테스트할 필요가 있나요~?

2021-09-09 06:03 UTC, js87zz commented on packages/toast-ui.grid/cypress/integration/export.spec.ts
> +      });
`onlyFiltered`랑 사용하는 경우도 `onlySelected`가 우선시 되는거죠?

2021-09-09 06:04 UTC, js87zz commented on packages/toast-ui.grid/cypress/integration/export.spec.ts
> +        cy.gridInstance().invoke('export', format, { onlyFiltered: true });
이 옵션도 다른 옵션이랑 조합한 테스트가 추가되면 좋겠어요~

2021-09-09 06:05 UTC, js87zz commented on packages/toast-ui.grid/cypress/plugins/index.js
> +          },
이 이슈는 이제 없을 것 같은데 이전으로 롤백해도 될 것 같습니다~!

2021-09-09 06:05 UTC, js87zz commented on packages/toast-ui.grid/docs/ko/README.md
> +- [💾 내보내기](export.md)
경로는 동일하게 맞춰주세요ㅎㅎ

2021-09-09 06:07 UTC, js87zz commented on packages/toast-ui.grid/examples/example27-export.html
> +    });
이렇게만 보면 예제가 뭔지 보기 어려우니까, 옵션 몇 개 대표적으로 추가해서 컨텍스트 메뉴에 커스터마이징해서 보여주는게 좋겠어요.

2021-09-09 06:07 UTC, js87zz commented on packages/toast-ui.grid/examples/example27-export.html
> +        target="_blank">here</a>
여기 튜토리얼 링크 수정 부탁드려요~!

2021-09-09 06:17 UTC, js87zz commented on packages/toast-ui.grid/types/options.d.ts
> +  exportData?: OptExport;
삭제해야겠네요~

2021-09-09 06:20 UTC, js87zz commented on packages/toast-ui.grid/types/options.d.ts
> +  exportData?: OptExport;
`types/index.d.ts` Grid 쪽에 API 추가한 것 타입에 반영 부탁드려요~

2021-09-09 06:23 UTC, js87zz commented on packages/toast-ui.grid/src/grid.tsx
> +   *    @param {string} options.fileName - File name to export
`[options.includeHeader=true]` 처럼 디폴트 값도 같이 명시 부탁드려요~!

2021-09-09 06:24 UTC, js87zz commented on packages/toast-ui.grid/src/helper/browser.ts
> +export function isSupportWindowNavigatorMsSaveOrOpenBlob() {
`isSupportMsSaveOrOpenBlob()` 정도로 줄여도 충분할 것 같습니다ㅎㅎ

2021-09-09 06:28 UTC, js87zz commented on packages/toast-ui.grid/src/dispatch/export.ts
> +export function exportCsv(fileName: string, targetText: string) {
이 함수랑 `exportExcel`은 export 할 필요 없지 않나요?

2021-09-09 06:33 UTC, js87zz commented on packages/toast-ui.grid/src/dispatch/export.ts
> +function getColumnNamesAndHeaders(
함수명이 좀 더 명시적이었으면 좋겠어요. 옵션에 따른 컬럼을 추출하는거니까 해당 동작이 더 잘 나타나면 좋겠고, 이런 조회성 함수는 `query/export` 계층에 따로 작성하면 좋겠네요!

2021-09-09 06:35 UTC, js87zz commented on packages/toast-ui.grid/src/dispatch/export.ts
> +  const sortExp = /\(desc\)|\(asc\)/;
그리드 정규식 변수명이 다 제각각인데 나중에 통일해야겠네요..
`re`프리픽스 붙여서 `reSort`로 통일하는게 어떤가요?

2021-09-09 06:41 UTC, js87zz commented on packages/toast-ui.grid/src/dispatch/export.ts
> +    columnNames = column.allColumns
기존 파라미터를 덮어쓰는 것보다는 의미에 맞는 새로운 변수를 선언해서 사용하는게 명확하겠네요. 가급적 이런 패턴은 지양하는 게 좋습니다~!

2021-09-09 06:47 UTC, js87zz commented on packages/toast-ui.grid/src/dispatch/export.ts
> +    .map((colInfo) => colInfo.header.replace(sortExp, ''));
개인적으로 forEach 문이나 reduce 문 안에서 한번에 다 구하는게 좋을 것 같네요. 불필요한 순회문이 많은 느낌이네요..ㅎㅎ

2021-09-09 06:52 UTC, js87zz commented on packages/toast-ui.grid/src/dispatch/export.ts
> +          (includeHiddenColumns || !colInfo.hidden) && !isCheckboxOrDragColumn(colInfo.name)
isDraggableColumn && isCheckboxColumn 형태로 쓰는게 더 낫지 않을까요? 역할 별로 만들고 쓰는 쪽에서 조합하는게 좋을 것 같아서요. 이거는 대연씨가 판단해주세요ㅎㅎ

2021-09-09 07:01 UTC, js87zz commented on packages/toast-ui.grid/src/dispatch/export.ts
> +  };
함수 파라미터에서 기본값 설정하고 스프레드 연산자로 옵션 확장하는게 더 좋겠네요~!
```js
export function execExport(store: Store, format: 'csv' | 'xlsx', options = { ... }: OptExport) {
  // ...
  const exportOptions = { ...options, columnNames }
```

2021-09-09 07:06 UTC, js87zz commented on packages/toast-ui.grid/src/dispatch/export.ts
> +      return convertTextToData(getText(store));
`return convertTextToData(dataText);`로 써도 되겠네요~

2021-09-09 07:08 UTC, js87zz commented on packages/toast-ui.grid/src/dispatch/export.ts
> +  }
이 작업은 `reduce`문 사용하면 한번 순회하는 걸로 합칠 수 있겠네요~!

2021-09-09 07:13 UTC, js87zz commented on packages/toast-ui.grid/src/dispatch/export.ts
> +export function exportCsv(fileName: string, targetText: string) {
`exportCSV`로 똑같이 해도 좋을 것 같습니다!

2021-09-09 07:14 UTC, js87zz commented on packages/toast-ui.grid/src/dispatch/export.ts
> +  }
`isSupportWindowNavigatorMsSaveOrOpenBlob` 대신에 그냥 `download` 함수 자체를 하나 유틸로 만들어서 여기서 쓰는건 어때요?ㅎㅎ

2021-09-09 07:16 UTC, js87zz commented on packages/toast-ui.grid/src/dispatch/export.ts
> +    if (includeHeader && column.complexColumnHeaders.length === 0) {
`complexColumnHeaders`도 해체할당 미리 해두면 좋겠네요~

2021-09-09 07:24 UTC, adhrinae requested changes
리뷰 완료합니다.

2021-09-09 07:24 UTC, adhrinae commented on packages/toast-ui.grid/src/dispatch/export.ts
> +        if (!(merge.s.r === merge.e.r && merge.s.c === merge.e.c)) {
저도 동의합니다.

2021-09-09 07:24 UTC, adhrinae commented on packages/toast-ui.grid/src/dispatch/export.ts
> +    targetLink.click();
Safari의 경우 추가 대응이 필요할 수도 있어요. 이 코드 한번 검토해주세요.

https://github.com/kennethjiang/js-file-download/blob/0c20260f6f3dbbc94082f9f204e32322e7323294/file-download.js#L18-L24

2021-09-09 07:24 UTC, adhrinae commented on packages/toast-ui.grid/src/query/column.ts
> +  }
`Array(maxRowCount).fill().map(() => []);` 으로 더 쉽게 초기화시킬 수 있겠네요.

2021-09-09 07:24 UTC, adhrinae commented on packages/toast-ui.grid/src/helper/browser.ts
> +  return !!(window.navigator as NavigatorWithMsSaveOrOpenBlob).msSaveOrOpenBlob;
좀 더 명확한 타입 가드 함수를 만들 수 있어요.

```ts
export interface NavigatorWithMsSaveOrOpenBlob extends Navigator {
  msSaveOrOpenBlob: MsSaveOrOpenBlob;
}

export function isSupportWindowNavigatorMsSaveOrOpenBlob(navigator: Navigator) navigator is NavigatorWithMsSaveOrOpenBlob {
  return 'msSaveOrOpenBlob' in navigator;
}

// 실제 사용 시
if (isSupportWindowNavigatorMsSaveOrOpenBlob(window.naviagtor)) {
}
```

2021-09-09 07:24 UTC, js87zz commented on packages/toast-ui.grid/src/dispatch/export.ts
> +      console.error('Not found dependency "xlsx"');
`xlsx` 없을때 메세지가 출력 안되는데 확인 부탁드려요~

2021-09-09 07:33 UTC, js87zz commented on packages/toast-ui.grid/src/dispatch/export.ts
> +  hierachy = removeUnnecessaryColumns(hierachy, columnNames);
가독성 때문에 합쳐서 사용하지 않은 건가요?

2021-09-09 07:35 UTC, js87zz commented on packages/toast-ui.grid/src/query/column.ts
> +  }
안타깝게도 그리드는 따로 폴리필을 안써서...이대로 가야되겠네요..

2021-09-09 07:36 UTC, js87zz commented on packages/toast-ui.grid/src/query/column.ts
> +  const data: any[][] = [];
타입을 any로 한 이유가 있나요?

2021-09-09 07:37 UTC, js87zz commented on packages/toast-ui.grid/src/query/column.ts
> +  attr?: 'header' | 'name'
항상 헤더로 넘어오던데 구분할 필요가 있는건가요?

2021-09-09 07:38 UTC, js87zz commented on packages/toast-ui.grid/src/query/column.ts
> +      data[i].push(attr ? colInfo[attr] : colInfo);
`attr`이 항상 header 라서 이 부분 별도 처리가 필요없어보이는데 확인 부탁드려요

2021-09-09 07:40 UTC, js87zz commented on packages/toast-ui.grid/src/query/column.ts
> +  hierarchy.forEach((colunms) => {
이 반복문이랑 위에 초기화 반복문이랑 같이 합칠 수는 없나요?

2021-09-09 07:41 UTC, js87zz commented on packages/toast-ui.grid/src/dispatch/export.ts
> +function getComplexHeaderData(column: Column, columnNames: string[]) {
이 부분도 추출 대상 헤더라는게 명확하게 나타나면 좋을 것 같습니다. 애도 query로 가면 좋겠네요ㅎㅎ

2021-09-09 07:44 UTC, js87zz commented on packages/toast-ui.grid/src/dispatch/export.ts
> +    });
지금보니까 이벤트를 멈췄을 때, 다운로드할 수 있는 함수가 없는 것 같네요. 비동기로 데이터 추가해서 제어하고 싶은 경우에는 `export`와 같은 프로퍼티로 함수를 넘겨줘야겠네요

2021-09-09 07:46 UTC, js87zz commented on packages/toast-ui.grid/src/dispatch/export.ts
> +}
합쳐도 되지 않나요?

2021-09-09 07:52 UTC, js87zz commented on packages/toast-ui.grid/src/dispatch/export.ts
> +    const dataText = getText(store);
`getText`함수는 copy 옵션이 적용된 결과를 반환할 거라 이 함수 그대로 사용하면 안될거에요. 
내부적으로 `getTextWithCopyOptionsApplied`함수를 안타고 formttedValue 기준으로만 데이터 추출하는 걸로 변경하면 될 것 같습니다.

2021-09-09 07:56 UTC, js87zz commented on packages/toast-ui.grid/src/dispatch/export.ts
> +      data: targetData,
2차원 문자열이 아니라 사용자가 커스터마이징할 때는 기존 데이터 구조가 유지되는게 좋을 것 같은데 해당 방식으로 넘겨주도록 수정하는게 사용하기 더 좋을 것 같습니다. `[{column: 'a', ...}, {column: 'b', ...}]`

2021-09-09 07:58 UTC, js87zz commented on packages/toast-ui.grid/src/dispatch/export.ts
> +function getMergeObject(complexColumnHeaderData: string[][]) {
요것도 함수명이 더 명확하면 좋겠네요

2021-09-09 07:59 UTC, js87zz commented on packages/toast-ui.grid/src/dispatch/export.ts
> +  const numOfColumn = complexColumnHeaderData[0].length;
첫번째 행이랑 다른 행들의 자식 컬럼 길이는 항상 같은거죠? 혹시나 확인 차원에서 여쭤봐요

2021-09-09 08:00 UTC, js87zz commented on packages/toast-ui.grid/src/dispatch/export.ts
> +      if (compareColumnName !== '') {
`if (compareColumnName) {` 로 써도 되겠네요~

2021-09-09 08:02 UTC, js87zz commented on packages/toast-ui.grid/src/dispatch/export.ts
> +        }
인덱스에 1을 더해주거나 빼주거나 하는게 sheetjs 의 인덱스랑 달라서 그런 것 같은데 이 부분은 주석으로 설명이 있으면 좋겠네요

2021-09-09 08:05 UTC, js87zz commented on packages/toast-ui.grid/src/dispatch/export.ts
> +      const compareColumnName = complexColumnHeaderData[rowIndex][colIndex];
컬럼명만 미리 매핑해놓은 구조를 만들어 두면 아래에서 중첩된 반복문을 줄일 수 있지 않나요?

2021-09-09 08:55 UTC, jwlee1108 reviewed
리뷰 완료합니다. 

다른 분들이 자세히 남겨주셔서 간단한 거 외 추가 의견은 없습니다.

2021-09-09 08:55 UTC, jwlee1108 commented on packages/toast-ui.grid/src/dispatch/export.ts
> +interface Merge {
`start`, `end`, `row`, `column`인가요? 간단하게나마 주석을 남겨놔도 괜찮을 것 같아요.

2021-09-09 08:55 UTC, jwlee1108 commented on packages/toast-ui.grid/src/dispatch/export.ts
> +  const sortExp = /\(desc\)|\(asc\)/;
음 `reg`로 하면 어떨까요? 뭔가 `re`는 재정렬 느낌이 납니다.

2021-09-09 08:58 UTC, jajugoguma commented on packages/toast-ui.grid/cypress/integration/export.spec.ts
> +    });
바로 리턴하는 것으로 변경했습니다.

2021-09-09 08:58 UTC, jajugoguma commented on packages/toast-ui.grid/cypress/integration/export.spec.ts
> +      it(`should export data according to defulat export options to '${format}'`, () => {
오타 수정 했습니다.

2021-09-09 08:59 UTC, jajugoguma commented on packages/toast-ui.grid/docs/ko/export.md
> +엑셀 내보내기는 복합 컬럼을 지원하지만 CSV 내보내지는 이를 지원하지 않는다. 만약 복합 컬럼을 사용하는 중에 CSV 내보내기를 수행하면 컬럼 헤더는 내보내지 않는다.
오타 수정했습니다.

2021-09-09 09:00 UTC, jajugoguma commented on packages/toast-ui.grid/src/dispatch/export.ts
> +  } else if (columnNames.length === 0) {
저도 명확하게 0과 비교하는게 더 좋다고 생각했습니다.
다른 분들의 의견은 어떠신가요?

2021-09-09 09:00 UTC, jajugoguma commented on packages/toast-ui.grid/src/dispatch/export.ts
> +        if (!(merge.s.r === merge.e.r && merge.s.c === merge.e.c)) {
의견 주신 조건으로 변경했습니다.

2021-09-09 09:01 UTC, jajugoguma commented on packages/toast-ui.grid/src/dispatch/export.ts
> +    if (includeHeader && column.complexColumnHeaders.length === 0) {
@lja1018 
명확하게 0과 비교하는게 좋다고 생각했습니다. 다른 분들의 의견은 어떠신가요?

@js87zz 
미리 해체할당 하는 것으로 변경했습니다.

2021-09-09 09:01 UTC, jajugoguma commented on packages/toast-ui.grid/src/dispatch/export.ts
> +  } else if (format === 'xlsx') {
`else` 만 사용하는 것으로 변경했습니다.

2021-09-09 09:02 UTC, jajugoguma commented on packages/toast-ui.grid/cypress/integration/export.spec.ts
> +        getMenuItemByText(`${formatToType(format)} Export`).click();
해당 동작을 수행하는 함수를 만들어 사용하는 것으로 변경했습니다.

2021-09-09 09:02 UTC, jajugoguma commented on packages/toast-ui.grid/cypress/integration/export.spec.ts
> +  describe('Without column headers', () => {
테스트 설명에 옵션 병기를 추가 했습니다.

2021-09-09 09:03 UTC, jajugoguma commented on packages/toast-ui.grid/cypress/integration/export.spec.ts
> +      it(`should export data of selected range to '${format}' regardless of "includeHiddenColumns" and "columnNames" options`, () => {
가이드에 우선순위에 대한 주의사항 추가했습니다.

2021-09-09 09:03 UTC, jajugoguma commented on packages/toast-ui.grid/cypress/integration/export.spec.ts
> +      });
셀 선택 여부에 따라 테스트를 재그룹핑 했습니다.

`onlyFiltered`랑 사용하는 경우 `onlySelected`가 우선시 되는 것이 맞습니다!

2021-09-09 09:04 UTC, jajugoguma commented on packages/toast-ui.grid/cypress/plugins/index.js
> +          },
설정 롤백 했습니다!

2021-09-09 09:04 UTC, jajugoguma commented on packages/toast-ui.grid/docs/ko/README.md
> +- [💾 내보내기](export.md)
경로 동일하게 수정 했습니다.

2021-09-09 09:04 UTC, jajugoguma commented on packages/toast-ui.grid/examples/example27-export.html
> +        target="_blank">here</a>
예제 링크를 우선 영문 튜토리얼로 수정했는데 영문 튜토리얼 작성이 아직 되지 않았습니다. 어떻게 하는 것이 좋을까요??

2021-09-09 09:05 UTC, jajugoguma commented on packages/toast-ui.grid/types/options.d.ts
> +  exportData?: OptExport;
해당 코드 삭제하고 `types/index.d.ts`에 추가한 API의 타입 반영 했습니다.

2021-09-09 09:05 UTC, jajugoguma commented on packages/toast-ui.grid/src/grid.tsx
> +   *    @param {string} options.fileName - File name to export
우선 디폴트 값 명시했습니다.

2021-09-09 09:05 UTC, jajugoguma commented on packages/toast-ui.grid/src/helper/browser.ts
> +export function isSupportWindowNavigatorMsSaveOrOpenBlob() {
말씀해주신 이름으로 변경했습니다!

2021-09-09 09:06 UTC, jajugoguma commented on packages/toast-ui.grid/src/dispatch/export.ts
> +export function exportCsv(fileName: string, targetText: string) {
기존에 스텁을 하기 위해 export 했었습니다.
`export` 삭제 했습니다!

2021-09-09 09:07 UTC, jajugoguma commented on packages/toast-ui.grid/src/dispatch/export.ts
> +  const sortExp = /\(desc\)|\(asc\)/;
우선 `reSort`로 변경 했으나 저도 이것이 재정렬을 의미하는 것처럼 느껴져서 `regSort`로 변경하도록 하겠습니다.

2021-09-09 09:07 UTC, jajugoguma commented on packages/toast-ui.grid/src/dispatch/export.ts
> +    columnNames = column.allColumns
새로운 변수를 선언해서 사용하는 것으로 변경했습니다!

2021-09-09 09:08 UTC, jajugoguma commented on packages/toast-ui.grid/src/dispatch/export.ts
> +    .map((colInfo) => colInfo.header.replace(sortExp, ''));
`forEach` 문 내에서 한번에 구하는 것으로 변경했습니다!

2021-09-09 09:08 UTC, jajugoguma commented on packages/toast-ui.grid/src/dispatch/export.ts
> +          (includeHiddenColumns || !colInfo.hidden) && !isCheckboxOrDragColumn(colInfo.name)
`isDraggableColumn && isCheckboxColumn`로 사용하는 것이 더 좋아보여 해당 방법으로 변경했습니다.

2021-09-09 09:08 UTC, jajugoguma commented on packages/toast-ui.grid/src/dispatch/export.ts
> +      return convertTextToData(getText(store));
제가 놓친 부분이었네요... 수정했습니다!

2021-09-09 09:08 UTC, jajugoguma commented on packages/toast-ui.grid/docs/ko/export.md
> +인자로 주어진 포맷과 내보내기 옵션에 따라 파일을 내보낸다. (`ExportOpt`의 인터페이스 구조는 [여기](https://github.com/nhn/tui.grid/blob/master/packages/toast-ui.grid/types/store/export.d.ts)을 참고한다.)
오타 수정 했습니다!

2021-09-09 09:09 UTC, jajugoguma commented on packages/toast-ui.grid/src/dispatch/export.ts
> +  hierachy = removeUnnecessaryColumns(hierachy, columnNames);
`filteredHierachy` 라는 이름의 변수를 사용하는 것으로 변경했습니다.

2021-09-09 09:09 UTC, jajugoguma commented on packages/toast-ui.grid/src/dispatch/export.ts
> +    columnNames = column.allColumns
다른 변수를 사용하는 것으로 변경했습니다.
기존 방법이 안티 패턴이라는 것을 배웠으니 추후에는 이렇게 사용하는 일이 없도록 하겠습니다!

2021-09-09 09:10 UTC, jajugoguma commented on packages/toast-ui.grid/src/helper/browser.ts
> +  return !!(window.navigator as NavigatorWithMsSaveOrOpenBlob).msSaveOrOpenBlob;
`navigator is NavigatorWithMsSaveOrOpenBlob` 작성시 에러가 발생해서 확인 후 다시 적용해보도록 하겠습니다!

2021-09-09 09:11 UTC, jajugoguma commented on packages/toast-ui.grid/src/dispatch/export.ts
> +      console.error('Not found dependency "xlsx"');
XLSX가 `default` 프로퍼티를 가진 객체로 넘어오는 것을 확인해서 사용중인 메서드 `writeFile`의 존재 여부를 확인 하는 것으로 변경했습니다.

2021-09-09 09:12 UTC, jajugoguma commented on packages/toast-ui.grid/src/query/column.ts
> +  const data: any[][] = [];
추후 사용을 고려해서 `any`로 두고 헤더 또는 이름 또는 컬럼 객체 배열을 받도록 구성했었는데 현재는 그럴 필요가 없어서 `string`으로 변형 했습니다.

2021-09-09 09:12 UTC, jajugoguma commented on packages/toast-ui.grid/src/query/column.ts
> +  attr?: 'header' | 'name'
추후 사용을 고려한것 이었는데 현재는 그럴 필요가 없어서 해당 인자를 받지 않고 `'header'`를 사용하는 것으로 변경 했습니다.

2021-09-09 09:13 UTC, jajugoguma commented on packages/toast-ui.grid/src/query/column.ts
> +      data[i].push(attr ? colInfo[attr] : colInfo);
추후 사용을 고려한것 이었는데 현재는 그럴 필요가 없어서 해당 인자를 받지 않고 `'header'`를 사용하는 것으로 변경 했습니다.

2021-09-09 09:13 UTC, jajugoguma commented on packages/toast-ui.grid/src/dispatch/export.ts
> +function getMergeObject(complexColumnHeaderData: string[][]) {
함수명을 `getMergeRelationships`로 변경 했습니다.

2021-09-09 09:14 UTC, jajugoguma commented on packages/toast-ui.grid/src/dispatch/export.ts
> +  const numOfColumn = complexColumnHeaderData[0].length;
네! 항상 동일합니다.

2021-09-09 09:14 UTC, jajugoguma commented on packages/toast-ui.grid/src/dispatch/export.ts
> +      if (compareColumnName !== '') {
해당 조건으로 변경 했습니다!

2021-09-10 08:17 UTC, jajugoguma commented on packages/toast-ui.grid/cypress/integration/export.spec.ts
> +function formatToType(format: string) {
해당 동작을 수행하는 `clickExportMenuItemByFormat` 내부에서 수행하도록 변경했습니다.

2021-09-10 08:17 UTC, jajugoguma commented on packages/toast-ui.grid/cypress/integration/export.spec.ts
> +        cy.gridInstance().invoke('export', format, { onlyFiltered: true });
다른 옵션과 섞은 테스트 추가했습니다.

2021-09-10 10:11 UTC, jajugoguma commented on packages/toast-ui.grid/src/dispatch/export.ts
> +        }
컬럼명을 값으로 가진 2차원 배열에서 가장 먼저나오는 값을 기준으로 그 이후(행, 열로 한칸 씩 다음 부터) 값이 같아 병합해야하는 셀인지 확인 하기 위해 인덱스에 1을 더해 줍니다.

2021-09-10 10:13 UTC, jajugoguma commented on packages/toast-ui.grid/src/dispatch/export.ts
> +      const compareColumnName = complexColumnHeaderData[rowIndex][colIndex];
병합된 셀인지 확인하기 위해서는 가장 먼저 나오는 값을 기준으로 그 이후에 나오는 값(행과 열에 대해서)을 검사하기 때문에 가장 먼저 나오는 값을 찾고 이후에 나오는 값들을 검증하기 위해서 위와 같은 방법으로 구현했습니다.

2021-09-10 10:14 UTC, jajugoguma commented on packages/toast-ui.grid/src/dispatch/export.ts
> +    });
`exportCallback` 함수를 콜백 함수로 전달해서 데이터 변경 시 해당 데이터로 다운로드 할 수 있도록 변경했습니다.

2021-09-10 10:15 UTC, jajugoguma commented on packages/toast-ui.grid/src/dispatch/export.ts
> +function getComplexHeaderData(column: Column, columnNames: string[]) {
`getHeaderDataFromComplexColumn` 이라는 이름으로 변경하고 query로 이동 했습니다.

2021-09-10 10:15 UTC, jajugoguma commented on packages/toast-ui.grid/src/dispatch/export.ts
> +function getColumnNamesAndHeaders(
`getNamesAndHeadersOfColumnsByOptions`라는 이름으로 변경하고 query로 이동했습니다.

2021-09-10 10:16 UTC, jajugoguma commented on packages/toast-ui.grid/src/dispatch/export.ts
> +  }
`download`라는 이름의 함수를 `helper/browser`에 만들어 사용하는 것으로 변경했습니다.

2021-09-10 10:17 UTC, jajugoguma commented on packages/toast-ui.grid/src/dispatch/export.ts
> +    targetLink.click();
해당 코드 사용하는 것으로 변경했습니다.

2021-09-10 10:17 UTC, jajugoguma commented on packages/toast-ui.grid/src/dispatch/export.ts
> +  hierachy = removeUnnecessaryColumns(hierachy, columnNames);
가독성이 나빠져서 위처럼 분리해서 사용했습니다.

2021-09-10 10:17 UTC, jajugoguma commented on packages/toast-ui.grid/src/query/column.ts
> +  hierarchy.forEach((colunms) => {
아래 반복문에 조건문을 추가해 하나의 반복문으로 합쳤습니다.

2021-09-10 10:18 UTC, jajugoguma commented on packages/toast-ui.grid/src/dispatch/export.ts
> +}
`emitExportByType`으로 변경하면서 하나의 함수로 통합했습니다.

2021-09-10 10:21 UTC, jajugoguma commented on packages/toast-ui.grid/src/dispatch/export.ts
> +    const dataText = getText(store);
해당 함수를 잘 보니 제가 필요한 부분은 그렇게 많지 않고 굳이 텍스트로 받은 후 배열로 변환할 필요가 없어서 조건문 내부에서 범위 내의 데이터를 가져오는 방식으로 변경했습니다.
컬럼의 경우 이미 범위에 해당하는 컬럼명을 가져오고 필터 시 `filteredRawData`를 가져와서 복잡한 로직이 필요 없다고 판단했습니다.

2021-09-10 10:21 UTC, jajugoguma commented on packages/toast-ui.grid/src/dispatch/export.ts
> +interface Merge {
해당 내용을 담은 주석 추가했습니다.

2021-09-10 10:30 UTC, jajugoguma commented on packages/toast-ui.grid/src/dispatch/export.ts
> +  }
`reduce` 문 사용하는 것으로 변경했습니다!

2021-09-15 00:05 UTC, js87zz commented on packages/toast-ui.grid/src/dispatch/export.ts
> +      exportCallback(exportingData, 'csv', exportOptions);
`data`만 인자로 받는 형태로 변경

2021-09-15 04:36 UTC, merged