fix: error occurs on usageStatistics in incognito mode (fix #1450)
nhn/tui.grid pull request #1500
Opened 2021-11-04 01:36 UTC by jajugoguma

### Please check if the PR fulfills these requirements
- [x] It's submitted to right branch according to our branching model
- [x] It's right issue type on title
- [x] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [x] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes/features)
- [ ] Docs have been added/updated (for bug fixes/features)
- [ ] It does not introduce a breaking change or has description for the breaking change

### Description

- Fix a script error that occurred when third-party cookies were blocked in incognito mode.
  - If browser is set to block third-party cookies, do nothing.

---
Thank you for your contribution to TOAST UI product. 🎉 😘 ✨

2021-11-04 03:11 UTC, adhrinae requested changes
리뷰 완료합니다.

2021-11-04 03:11 UTC, adhrinae commented on packages/toast-ui.grid/src/helper/googleAnalytics.ts
> +    const date = window.localStorage.getItem(applicationKeyForStorage);
`try/catch` 를 쓰지 말고 여기서 `window?.localStorage?.getItem` 으로 접근하는게 나아 보입니다.

어떤 부분에서 에러가 날지 모르는 블락 전체를 `try/catch` 로 감싸버리면 나중에 직접 디버깅해야하는 에러가 발생할 때 원인을 찾게 어렵도록 만들거든요.

2021-11-04 03:30 UTC, jajugoguma commented on packages/toast-ui.grid/src/helper/googleAnalytics.ts
> +    const date = window.localStorage.getItem(applicationKeyForStorage);
크롬 시크릿 모드에서 서드파티 쿠키를 막으면 `windows.localStorage`에 접근할 때 프로퍼티를 찾지 못해 에러가 발생하는 것이 아니라 접근 행위 자체에 강제로 SecurityError를 발생시키는 것으로 보입니다.

그러나 지금처럼 모든 블럭을 `try/catch`로 묶는 것은 원인 파악에 문제가 있을 것으로 보이니 `windows.localStorage`에 처음 접근하는 코드만 감싸고 에러 발생 시 return 하는 것으로 변경하겠습니다.

2021-11-04 06:55 UTC, jwlee1108 reviewed
리뷰 완료합니다. 리뷰 반영하고 다시 확인해볼께요.

2021-11-05 01:19 UTC, js87zz commented on packages/toast-ui.grid/src/helper/googleAnalytics.ts
> +    window.localStorage.setItem(applicationKeyForStorage, String(new Date().getTime()));
`localStorage.getItem()`호출할 때 체크해야하지 않나요~?

2021-11-05 01:20 UTC, js87zz commented on packages/toast-ui.grid/src/helper/googleAnalytics.ts
> +    //If browser is set to block third-party cookies, do nothing.
`//` 다음에 한 칸 띄면 좋겠네요ㅎㅎ

2021-11-05 01:21 UTC, jwlee1108 commented on packages/toast-ui.grid/src/helper/googleAnalytics.ts
> +    window.localStorage.setItem(applicationKeyForStorage, String(new Date().getTime()));
이게 전에꺼보면 `localStorage`에 접근하는 순간 에러가 발생해서 `try` 블럭에 넣은 것 같은데 맞나요?

2021-11-05 04:04 UTC, adhrinae commented on packages/toast-ui.grid/src/helper/googleAnalytics.ts
> +    window.localStorage.setItem(applicationKeyForStorage, String(new Date().getTime()));
아예 로컬스토리지에 최초 접근하는 부분을 `try/catch` 로 감싼 함수로 분리하고, 거기서 에러가 발생할 시 `null` 혹은 `undefined` 를 리턴하는 방식으로 만든 다음 `sendHostname` 함수 바디에서는 그 값의 여부만으로 로직을 실행하는게 더 나아보입니다.

2021-11-05 07:32 UTC, jajugoguma commented on packages/toast-ui.grid/src/helper/googleAnalytics.ts
> +    window.localStorage.setItem(applicationKeyForStorage, String(new Date().getTime()));
`date`를 가져오기 위해 `localStorage`에 최초로 접근하는 부분을 함수로 분리 후 에러 발생시 `null`을 반환하고, `date`가 `null`이면 함수를 종료하도록 변경했습니다.

2021-11-05 07:32 UTC, jajugoguma commented on packages/toast-ui.grid/src/helper/googleAnalytics.ts
> +    //If browser is set to block third-party cookies, do nothing.
주석에 `//` 다음에 공백 추가했습니다.

2021-11-05 07:39 UTC, jwlee1108 approved these changes
리뷰 완료합니다. 고생많으셨어요.

2021-11-05 07:39 UTC, jwlee1108 commented on packages/toast-ui.grid/src/helper/googleAnalytics.ts
> +  if ((date && !isExpired(Number(date))) || !date) {
`!date`인데 falsy 관련 이슈 있는지만 체크해보면 될 것 같습니다.

2021-11-05 11:54 UTC, merged