feat: disable context menu (fix #1432)
nhn/tui.grid pull request #1515
Opened 2021-11-15 09:05 UTC by jajugoguma

### Please check if the PR fulfills these requirements
- [x] It's submitted to right branch according to our branching model
- [x] It's right issue type on title
- [x] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [x] The commit message follows our guidelines
- [x] Tests for the changes have been added (for bug fixes/features)
- [x] Docs have been added/updated (for bug fixes/features)
- [ ] It does not introduce a breaking change or has description for the breaking change

### Description

- Added feature to disable context menu
  - Disable the context menu by passing `null` to the `contextMenu` option.
  - If disable the context menu, the browser default context menu appears when right-click.

**To-Be**
![](https://user-images.githubusercontent.com/41339744/141752767-b236c48f-ea0f-4cfb-a041-b6754bcab123.gif)

---

Thank you for your contribution to TOAST UI product. 🎉 😘 ✨

2021-11-16 06:04 UTC, adhrinae requested changes
리뷰 완료합니다.

2021-11-16 06:04 UTC, adhrinae commented on packages/toast-ui.grid/src/view/contextMenu.tsx
> +  menuItems: menuItems || contextMenu!.flattenTopMenuItems,
이건 옵셔널 체닝 활용 안해도 괜찮을까요?

2021-11-16 06:11 UTC, lja1018 reviewed
리뷰 완료합니다.

2021-11-16 06:11 UTC, lja1018 commented on packages/toast-ui.grid/docs/ko/contextMenu.md
> +`contextMenu` 옵션은 함수가 되어야 하며, 함수의 반환값은 아래와 같은 2차원 배열이어야 한다.
```suggestion
`contextMenu` 옵션은 함수나 null이 되어야 하며, 함수의 반환값은 아래와 같은 2차원 배열이어야 한다.
```
는 어떤가요? 아래에 null일 때 동작을 알려주긴 하는데 옵션 자체는 함수나 null이 될 수 있으니까요.

2021-11-16 07:29 UTC, js87zz commented on packages/toast-ui.grid/docs/ko/contextMenu.md
> +`contextMenu` 옵션이 `null`이면 컨텍스트 메뉴는 비활성화 된다.
이 경우 브라우저 기본 컨텍스트 메뉴가 활성화된다는 점을 알려주고 이미지도 보여주면 좋곘네요ㅎㅎ

2021-11-16 07:35 UTC, js87zz commented on packages/toast-ui.grid/src/store/contextMenu.ts
> +        createMenuGroups: createMenuGroups || createDefaultContextMenu,
`createMenuGroups` 프로퍼티를 `null`로 설정하는게 더 낫지 않나요? 가져다 쓰는 쪽에서는 타입을 일관되게 유지할 수 있도록 하는게 이득이 될 것 같아서요.

2021-11-16 07:37 UTC, js87zz commented on packages/toast-ui.grid/types/store/index.d.ts
> +  readonly contextMenu: ContextMenu | null;
위에서 언급한 것처럼 `ContextMenu`로 타입을 통일하고 스토어 안에서 분기처리하는게 사용하는 쪽에서 좀 더 일관성있게 할 수 있지 않을까요?

2021-11-16 07:38 UTC, js87zz commented on packages/toast-ui.grid/src/view/container.tsx
> +        target.dispatchEvent(mouseupEvent);
mouseup 발생했을 때 실행되는 dispatch들을 호출하는게 더 가독성에 좋을 것 같습니다.

2021-11-16 07:38 UTC, js87zz approved these changes
리뷰 완료입니다! 고생하셨어요~

2021-11-17 01:45 UTC, jajugoguma commented on packages/toast-ui.grid/src/store/contextMenu.ts
> +  return isNull(createMenuGroups)
기존 타입 유지하면서 내부 프로퍼티 값을 다르게 하는 것으로 변경하면서 긴 로직에 대한 삼항 연산자 제거했습니다.

2021-11-17 01:46 UTC, jajugoguma commented on packages/toast-ui.grid/src/view/container.tsx
> +      if (target) {
곰곰히 생각해보니 `target`같은 요소가 없을 상황이 없어서 해당 조건문 제거했습니다.

2021-11-17 01:47 UTC, jajugoguma commented on packages/toast-ui.grid/src/view/contextMenu.tsx
> +  menuItems: menuItems || contextMenu!.flattenTopMenuItems,
기존에는 해당 내부 로직으로 들어올 일이 없어서 옵셔널 체이닝을 사용하지 않았지만, 변경된 코드에서는 그렇지 않기 때문에 옵셔널 체이닝을 사용하는 것으로 변경했습니다.

2021-11-17 01:47 UTC, jajugoguma commented on packages/toast-ui.grid/docs/ko/contextMenu.md
> +`contextMenu` 옵션은 함수가 되어야 하며, 함수의 반환값은 아래와 같은 2차원 배열이어야 한다.
말씀해주신 내용으로 변경했습니다.

2021-11-17 01:48 UTC, jajugoguma commented on packages/toast-ui.grid/docs/ko/contextMenu.md
> +`contextMenu` 옵션이 `null`이면 컨텍스트 메뉴는 비활성화 된다.
브라우저 기본 컨텍스트가 활성화 된다는 것을 명시하고, 관련된 이미지 추가했습니다.

2021-11-17 01:49 UTC, jajugoguma commented on packages/toast-ui.grid/src/store/contextMenu.ts
> +        createMenuGroups: createMenuGroups || createDefaultContextMenu,
결국 `createMenuGroups`가 null로 넘어오는 상황이었어서 가져다 쓰는 쪽에서는 타입을 일관되게 유지할 수 있도록 `ContextMenu`의 타입 정의에서 `null`을 제거하고 `CreateMenuGroups` 타입 정의에 `null`을 추가했습니다.

2021-11-17 01:50 UTC, jajugoguma commented on packages/toast-ui.grid/types/store/index.d.ts
> +  readonly contextMenu: ContextMenu | null;
위에 언급한 것 처럼 `ContextMenu`의 타입 정의에서 `null`을 제거하고 `CreateMenuGroups` 타입 정의에 `null`을 추가했습니다.

2021-11-17 01:54 UTC, jajugoguma commented on packages/toast-ui.grid/src/view/container.tsx
> +        target.dispatchEvent(mouseupEvent);
`mouseup`이 발생됐을 때 `mousemove` 등에 할당한 핸들러를 제거해주어야 합니다. 그러나 `mouseup` 이벤트에 할당된 핸들러인 `clearDocumentEvents`가 `private` 이고 이를 `public`으로 변경하는게 좋을 것 같지 않아서 기존 처럼 `mouseup`을 발생 시키는 것으로 유지 했습니다.
다만, 가독성 개선을 위해 `helper/mouse`에 `emitMouseup` 함수를 추가하고 이를 호출하는 것으로 변경 했습니다.

2021-11-18 09:37 UTC, merged