feat: enable/disable specific cell
nhn/tui.grid pull request #1530
Opened 2021-11-29 07:51 UTC by jajugoguma

### Please check if the PR fulfills these requirements
- [x] It's submitted to right branch according to our branching model
- [x] It's right issue type on title
- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [x] The commit message follows our guidelines
- [x] Tests for the changes have been added (for bug fixes/features)
- [ ] Docs have been added/updated (for bug fixes/features)
- [ ] It does not introduce a breaking change or has description for the breaking change

### Description

* Added API to enable/disable specific cell.
  * Worked by using the basic logic of the row and column disable function.
  * If that the cell is in a row number or draggable column, do nothing.

**Disable cell**
![](https://user-images.githubusercontent.com/41339744/143827940-f8eb2193-96c4-44a9-8576-573393f74608.gif)

**enable cell**
![](https://user-images.githubusercontent.com/41339744/143827892-dd245835-8a72-4cb2-93d0-81d0a963d2fe.gif)

---

Thank you for your contribution to TOAST UI product. 🎉 😘 ✨

2021-11-30 01:10 UTC, adhrinae requested changes
리뷰 완료합니다.

2021-11-30 01:10 UTC, adhrinae commented on packages/toast-ui.grid/src/store/data.ts
> +  } else if (!isUndefined(row._disabledPriority[name])) {
이 정도면 `row_.disabledPriority[name]` 자체를 분기 태우기 이전에 변수로 빼놔도 되겠네요.

2021-11-30 08:22 UTC, lja1018 approved these changes
리뷰 완료합니다.

2021-11-30 08:22 UTC, lja1018 commented on packages/toast-ui.grid/src/dispatch/data.ts
> +  if (isRowNumColumn(columnName) || isDragColumn(columnName)) {
위로 올려서 `store` 해체 전에 리턴시키는건 어떠신가요? 그냥 제안입니다.

2021-11-30 08:22 UTC, lja1018 commented on packages/toast-ui.grid/src/store/data.ts
> +  if (_disabledPriority === 'CELL') {
`'CELL'` 상수화하는건 어떤가요?

2021-12-03 01:23 UTC, jwlee1108 approved these changes
리뷰 완료합니다.

2021-12-03 01:23 UTC, jwlee1108 commented on packages/toast-ui.grid/src/store/data.ts
> +const DISABLEDPRIORITY_BLANK = '';
`DISABLED_PRIORITY_BLANK`로 바꾸는 건 어때요? 밑에선 camelCase 사용할 때 `disablePriority`로 분리해서 사용되어 있네요.

2021-12-08 08:30 UTC, js87zz commented on packages/toast-ui.grid/cypress/integration/data.spec.ts
> +    cy.getCell(0, 'name').should('have.class', cls('cell-disabled'));
포커스 활성화 여부로는 검증할 수 없고, 에디팅 여부로 검증이 가능할 것 같은데 그렇게 되면 테스트 가독성이 떨어질것 같네요. 현재 그리드 Cypress에서는 testing library 기반으로 검증하고 있지 않아서 우선 클래스로 검증하는게 좋을 것 같습니다. role 이나 마크업이 어느정도 정돈이 된 다음에나 테스트 변경이 가능할 것 같네요.

2021-12-08 08:32 UTC, js87zz commented on packages/toast-ui.grid/src/dispatch/data.ts
> +  }
`if (row) {`로 감싸는게 어떤가요? 중간 리턴문이 많으면 아무래도 가독성이 떨어져서요. 저도 제안입니다.

2021-12-08 08:33 UTC, js87zz commented on packages/toast-ui.grid/src/dispatch/data.ts
> +  _disabledPriority[columnName] = disabled ? 'CELL' : '';
만든 상수 여기서도 쓰는게 명확하겠네요~

2021-12-08 08:36 UTC, js87zz commented on packages/toast-ui.grid/src/store/data.ts
> +const DISABLED_PRIORITY_BLANK = '';
좀 더 의미있는 네이밍으로 변경되면 좋겠어요.
`DISABLED_PRIORITY_NONE = 'NONE'`정도?

2021-12-08 08:38 UTC, js87zz commented on packages/toast-ui.grid/src/store/data.ts
> +  } else if (!isUndefined(_disabledPriority)) {
column, row 일때 조건문을 나누어서 값을 넣어주는게 더 명확할 것 같습니다.

2021-12-08 08:38 UTC, js87zz approved these changes
리뷰 완료입니다. 고생하셨어요!

2021-12-08 11:49 UTC, merged