feat: dynamic row span
nhn/tui.grid pull request #1535
Opened 2021-12-08 11:53 UTC by jajugoguma

### Please check if the PR fulfills these requirements
- [x] It's submitted to right branch according to our branching model
- [x] It's right issue type on title
- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [x] The commit message follows our guidelines
- [x] Tests for the changes have been added (for bug fixes/features)
- [x] Docs have been added/updated (for bug fixes/features)
- [ ] It does not introduce a breaking change or has description for the breaking change

### Description

* Added feature to apply dynamic rowspan for selected columns.
* Can apply a dynamic rowspan to a column by passing an option in the form below.
```ts
const grid = new Grid({
  // ...,
  columns: [
      {
        header: 'Name',
        name: 'name',
        rowSpan: true
      },
      {
        header: 'Artist',
        name: 'artist',
        rowSpan: true
      }
    ],
  // ...
});
```

**Default**
Row span is applied to the selected column when creating the grid.

<img width="800" src="https://user-images.githubusercontent.com/41339744/145195724-95a31ddb-9429-4ade-aca4-b0bd22f6c40f.png">

**Filter**
When applying a filter, the row span is reapplied to the changed data.

![](https://user-images.githubusercontent.com/41339744/145195895-bd62f5c7-12e0-44eb-9468-b8f957593ac5.gif)

**D&D**
Reset all row spans at the start of dragging, and then reapplys the rowspans when dropping.

![](https://user-images.githubusercontent.com/41339744/145196027-8e4e2b36-d051-47ed-bc72-e0b09e2ac476.gif)

**Sort**
Reapplies rowspan to changed data when sorting.

![](https://user-images.githubusercontent.com/41339744/145196155-a51b211e-1a86-455c-968d-a747089115ab.gif)

**Pagination**
If the pages are different, a separate rowspan is applied even if the subsequent values are the same.

![](https://user-images.githubusercontent.com/41339744/145196260-f9223857-43ad-4a8e-9452-d95c0dec3f70.gif)

**Edit**
If the cell value changes, the row span is reapplied accordingly.
If you change the cell value to which the rowspan is applied, only the cell value of the top row among the rows bounded by the rowspan is changed.

![](https://user-images.githubusercontent.com/41339744/145196389-b67242db-9b97-4433-ac5a-03a890f85e0a.gif)

**Realtion columns**
Dynamic rowspan is not applied to sub-columns except for the column in the top-level relation within the column relation.

<img width="800" src="https://user-images.githubusercontent.com/41339744/145196470-d7a7f437-d096-48c0-b40f-da8aeece25b2.png">

**Tree**
For tree data, row span is not applied.

---
Thank you for your contribution to TOAST UI product. 🎉 😘 ✨

2021-12-09 05:52 UTC, jwlee1108 reviewed
리뷰 완료합니다. 고생 많으셨어요.

2021-12-09 05:52 UTC, jwlee1108 commented on packages/toast-ui.grid/docs/ko/row-span.md
> +## 로우 스팬 동작
굳이 한글로 로우 스팬이라고 써야 하나 싶네요. `rowspan`이라고 해도 무방할 것 같아요.

2021-12-09 05:52 UTC, jwlee1108 commented on packages/toast-ui.grid/docs/ko/row-span.md
> +[여기](http://nhn.github.io/tui.grid/latest/tutorial-example29-dynamic-row-span)서 로우 스팬 예제를 확인할 수 있다.
rowspan 예제는 [링크](http://nhn.github.io/tui.grid/latest/tutorial-example29-dynamic-row-span)를 통해 확인할 수 있다.

이렇게 하면 어떨까요

2021-12-09 05:52 UTC, jwlee1108 commented on packages/toast-ui.grid/docs/ko/row-span.md
> +> **deprecated 됨** 컬럼 옵션으로 적용하라.
`됨`은 빼도 될 것 같아요. 

> **deprecated** 컬럼 옵션 사용 

이렇게 바꾸면 어때요

2021-12-09 06:26 UTC, lja1018 approved these changes
리뷰 완료합니다.
고생 많으셨어요.

2021-12-09 06:26 UTC, lja1018 commented on packages/toast-ui.grid/src/dispatch/column.ts
> +      optColumn.rowSpan
`optColumn`을 인자로 넘겨주던데 함수 내에서 프로퍼티 읽어서 사용해도 되지 않나요?

2021-12-09 06:26 UTC, lja1018 commented on packages/toast-ui.grid/src/dispatch/data.ts
> +      updateRowSpanWhenAppending(rawData, prevRow, options.extendPrevRowSpan || false);
L551에서 `extendPrevRowSpan` 뽑아도 되지 않나요?

2021-12-09 06:26 UTC, lja1018 commented on packages/toast-ui.grid/src/dispatch/rowSpan.ts
> +    !isEmpty(pageOptions) && !pageOptions.perPage ? DEFAULT_PER_PAGE : pageOptions.perPage;
`pageOptions.perPage` 변수에 담아서 써도 될 것 같습니다.
`const { perPage }  = pageOptions;`

2021-12-09 06:26 UTC, lja1018 commented on packages/toast-ui.grid/src/dispatch/rowSpan.ts
> +  (_attributes as RecursivePartial<RowAttributes & RowSpanAttribute>).rowSpan = rowSpan;
`RecursivePartial<RowAttributes & RowSpanAttribute>` 타입 따로 정의해놓고 사용해도 될 것 같습니다.
아래에도 쓰이고 있네요.

2021-12-09 13:42 UTC, jwlee1108 reviewed
리뷰 완료합니다. 고생 많으셨습니다.

2021-12-09 13:42 UTC, jwlee1108 commented on packages/toast-ui.grid/docs/ko/row-span.md
> +rowspan 예제는 [링크](http://nhn.github.io/tui.grid/latest/tutorial-example29-dynamic-row-span)를 통해 확인할 수 있다.
사소하지만..단어 통일을 `Row Span` -> `rowspan`으로 바꿔도 될 것 같네요.  이미 html table 스펙이기도 하고 크게 무리 없어보여요.

2021-12-09 13:42 UTC, jwlee1108 commented on packages/toast-ui.grid/docs/ko/row-span.md
> +[여기](http://nhn.github.io/tui.grid/latest/tutorial-example06-attributes)서 Row Span 예제를 확인할 수 있다.
이 부분도 이렇게 바꿔야 할 것 같아요.

rowspan 예제는 [링크](http://nhn.github.io/tui.grid/latest/tutorial-example29-dynamic-row-span)를 통해 확인할 수 있다.

2021-12-09 13:42 UTC, jwlee1108 commented on packages/toast-ui.grid/docs/ko/row-span.md
> +## 예제
여기만 h2인데 확인바랍니다.

2021-12-09 13:42 UTC, jwlee1108 commented on packages/toast-ui.grid/docs/ko/row-span.md
> +<img width="800" src="https://user-images.githubusercontent.com/41339744/145196470-d7a7f437-d096-48c0-b40f-da8aeece25b2.png">
이건 마크다운이 아닌 것 같은데 괜찮나요?

2021-12-09 13:42 UTC, jwlee1108 commented on packages/toast-ui.grid/src/dispatch/data.ts
> +  setTimeout(() => updateRowSpan(store));
이 함수 본체를 보면 루프가 중첩이기도 하고...데이터가 대량일 경우 렌더링 파이프라인을 깨먹을 것도 같은데 이건 추후 개선 과제로 가져가야 할 것 같아요.

https://developers.google.com/web/fundamentals/performance/rendering/optimize-javascript-execution?hl=ko

요건 참고삼아 한 번 읽어보시면 좋을 것 같아요. 요즘 lodash도 그렇고 타이머 사용하는 함수들은 raf를 사용하도록 바뀌고 있더라구요.

2021-12-09 13:42 UTC, jwlee1108 commented on packages/toast-ui.grid/src/query/rowSpan.ts
> +    if (mainRowValue !== value || (perPage && index !== 0 && index % perPage === 0)) {
이런 복잡한 로직은 변수로 치환해주면 가독성 있겠어요.

2021-12-09 13:42 UTC, jwlee1108 commented on packages/toast-ui.grid/src/store/column.ts
> +  }
삼항연산자 처리를 할 수 있을 것 같은데 이건 취향 차이니 편한대로 하면 될 것 같습니다. 조건식은 변수로 치환해도 될 것 같아요.

```js
const rowSpan = (!column.rowSpan || treeColumnOptions.name || includes(relationColumns, column.name) ? false : column.rowSpan;
```

2021-12-10 01:24 UTC, adhrinae requested changes
리뷰 완료합니다.

2021-12-10 01:24 UTC, adhrinae commented on packages/toast-ui.grid/src/dispatch/rowSpan.ts
> +        rowSpans[rowKey]![name] = rowSpanOfColumn[rowKey]![name];
로직 상 조건문에 걸렸으니 non-null assertion(`!`)이 필요 없는게 맞을텐데 이렇게 들어있으니 괜히 나중에 코드 수정할 때 불안요소로 남을거같아요.

가급적이면 좀 번거롭더라도 타입스크립트가 인식할 수 있는 별도의 타입 가드 함수를 만들어서 확실하게 `rowSpans[rowKey]` 값이 존재한다는걸 타입스크립트 컴파일러가 인식하도록 만드는게 좋겠어요.

```ts
// 실제 타입까진 제가 모르니까 ??? 으로 처리
function isRowSpanAvailable(rowSpan: ??? | null): rowSpan is ??? {
  // boolean 리턴
}
```

참고: https://www.typescriptlang.org/docs/handbook/2/narrowing.html#using-type-predicates

2021-12-10 01:24 UTC, adhrinae commented on packages/toast-ui.grid/src/grid.tsx
> +    setTimeout(() => this.dispatch('updateRowSpan'));
다시봐도 `updateRowSpan` 만 별도로 비동기 호출을 해주어야 한다는 부분이 마음에 걸리네요.
보면 이렇게 호출하는데도 있고 아닌데도 있고... 나중에는 결국 새로운 기능 추가하거나 수정할 때마다 어떤 디스패치가 제대로 동작하지 않으면 일단 `setTimeout` 부터 넣고 보는 버릇이 생길테고, 코드를 읽는 사람이 맥락을 이해하기 어렵게 만들거같아요.

가급적이면 이렇게 되는 원인을 파악해서 손보는게 제일 좋을거같고요. 옵저버블 데이터로 다루다보니 데이터의 변형과 실제 랜더링 시 변경이 잘 맞아떨어지지 않는 부분이 있는 것 같아서 깔끔하게 수정하는건 꽤 어렵겠네요.

2021-12-10 01:24 UTC, adhrinae commented on packages/toast-ui.grid/src/query/rowSpan.ts
> +  if (!isNull(mainRowKey) && rowSpan![columnName] !== 1) {
위에서도 썼지만 가급적이면 나중에 생길 디버깅 상황을 위해서라도 non-null assertion은 함부로 쓰지 않는게 좋겠어요.

2021-12-10 01:24 UTC, adhrinae commented on packages/toast-ui.grid/src/store/column.ts
> +    return createColumn(
굳이 일반 리턴문으로 바뀐 이유가 있나요?

2021-12-10 01:29 UTC, jwlee1108 commented on packages/toast-ui.grid/src/dispatch/data.ts
> +  setTimeout(() => updateRowSpan(store));
아 그렇네요 ㅠ

2021-12-10 05:39 UTC, jajugoguma commented on packages/toast-ui.grid/docs/ko/row-span.md
> +## 예제
트리까지는 rowspan 동작의 하위 내용이기 때문에 h3이고, 예제는 별도의 내용이기 때문에 h2입니다.

2021-12-10 05:41 UTC, jajugoguma commented on packages/toast-ui.grid/docs/ko/row-span.md
> +<img width="800" src="https://user-images.githubusercontent.com/41339744/145196470-d7a7f437-d096-48c0-b40f-da8aeece25b2.png">
넵, 실제로 이미지는 잘 나오며, 다른 동작에서 설명하는 이미지의 `width`가 `800px`이기 때문에 이를 통일 시켜주기 위해 위와 같이 작성했습니다.

2021-12-10 05:54 UTC, jajugoguma commented on packages/toast-ui.grid/src/dispatch/data.ts
> +  setTimeout(() => updateRowSpan(store));
초기 프로토타이핑시와 현재 동적 rowspan을 적용하는 로직이 바뀌었는데 그것을 감안하지 않아 잘 동작하던 코드를 사용한 것이 문제입니다. 실제로는 `setTimeout`을 사용하지 않아도 정상 동작하기 때문에 이를 사용하지 않는 것으로 수정하겠습니다.

2021-12-10 06:10 UTC, jajugoguma commented on packages/toast-ui.grid/src/grid.tsx
> +    setTimeout(() => this.dispatch('updateRowSpan'));
넵, 초기 프로토타이핑 시 `옵저버블 데이터로 다루다보니 데이터의 변형과 실제 랜더링 시 변경이 잘 맞아떨어지지 않는 부분` 때문에 `setTimeout`을 사용해 비동기로 호출했었어야 하는데 계속된 로직 변경으로 비동기 호출이 필요 없다는 사실을 망각했었습니다... 수정하도록 하겠습니다.
동적 rowspan을 각 row에 적용하더라도 실제 렌더링은 `notify` 호출시 발생하기 때문에 뷰의 정상 렌더링 여부와 관계없이 데이터만 올바르다면 정상적으로 동작하도록 작성되어 있습니다.

2021-12-10 08:24 UTC, merged