fix: editors with drop-down layer to follow scrolling
nhn/tui.grid pull request #1542
Opened 2022-01-03 07:39 UTC by jajugoguma

### Please check if the PR fulfills these requirements
- [x] It's submitted to right branch according to our branching model
- [x] It's right issue type on title
- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [x] The commit message follows our guidelines
- [x] Tests for the changes have been added (for bug fixes/features)
- [ ] Docs have been added/updated (for bug fixes/features)
- [ ] It does not introduce a breaking change or has description for the breaking change

### Description

* Fixed that where the position of the drop-down layer in the editor did not move when scrolling.
  * The drop-down layer moves as you scroll.
  * Hides the drop-down layer when the editing cell is moved out of the viewport by scrolling.

**As-Is**
![](https://user-images.githubusercontent.com/41339744/147908141-5dbbc665-adeb-469c-8b8d-ea8b7902b4d6.gif)

**To-Be**
![](https://user-images.githubusercontent.com/41339744/147907931-c3f44225-ee5b-418c-b5d3-769c366db7ae.gif)

---
Thank you for your contribution to TOAST UI product. 🎉 😘 ✨

2022-01-03 08:09 UTC, lja1018 approved these changes
리뷰 완료합니다.

2022-01-03 08:09 UTC, lja1018 commented on packages/toast-ui.grid/cypress/integration/editor.spec.ts
> +    cy.get(`.${cls('rside-area')} .${cls('body-area')}`)
`.${cls('rside-area', 'body-area')}` 로 줄일 수 있을 것 같습니다.

2022-01-03 08:09 UTC, lja1018 commented on packages/toast-ui.grid/cypress/integration/editor.spec.ts
> +      },
여기는 1줄로 안되나요? 위에는 `school` 빼고 다 1줄인데 어색해서요 ㅋㅋ

2022-01-03 08:09 UTC, lja1018 commented on packages/toast-ui.grid/src/helper/common.ts
> +  return value >= start && value <= end;
그냥 제안인데 `start <= value && value <= end`는 어떤가요? 사이에 있다는 의미가 더 잘 보이는 것 같아서요.

2022-01-04 06:09 UTC, adhrinae commented on packages/toast-ui.grid/src/helper/common.ts
> +  return value >= start && value <= end;
저도 재언씨 의견에 동의합니다.

2022-01-04 06:34 UTC, adhrinae requested changes
리뷰 완료합니다.

2022-01-04 06:34 UTC, adhrinae commented on packages/toast-ui.grid/cypress/integration/editor.spec.ts
> +    cy.get(`.${cls('rside-area')} .${cls('body-area')}`)
여기서는 `getByCls` 안 쓰는 이유가 따로 있나요? 아니면 API가 이름이랑 다르게 동작하나요?

2022-01-04 06:34 UTC, adhrinae commented on packages/toast-ui.grid/src/editor/dom.ts
> +  return { top: newLayerTop, left: newLayerLeft };
이 함수는 결국 `layerEl` 에 새로운 값을 할당하는 것과 동시에 새로운 레이어의 좌표값을 리턴하는거네요?
굉장히 위화감이 많이 드는데, 그냥 이전 코드처럼 `setLayerPosition` 을 호출해서 `this.layer` 의 값을 변경한다음 바로 `this.layer.top`, `this.layer.left` 를 가져다 쓰는 방식으로 활용하지 않는 이유가 있었나요? 단순히 코드 줄을 줄이기 위해서라면 가독성과 유지보수 측면에서 더 손해 보는게 많을 구현으로 보입니다.

2022-01-04 06:34 UTC, adhrinae commented on packages/toast-ui.grid/src/editor/dom.ts
> +  if (initLayerPos) {
`moveLayer` 를 호출하는 코드는 모두 `initLayerPos` 의 여부를 확인한다음에 해당 함수를 호출하고 있는데 여기서 중복으로 체크할 필요가 있나요? `LayerPos` 타입도 항상 존재하는 값을 염두에 두고 있네요. 다른 방식의 처리가 되었으면 좋겠네요. 아예 이 함수를 호출하는 부분에서는 `if` 문을 빼버린다던지요.

2022-01-06 03:09 UTC, js87zz approved these changes
늦었지만 리뷰 완료입니다!

2022-01-06 03:09 UTC, js87zz commented on packages/toast-ui.grid/src/helper/common.ts
> +export function pixelToNumber(pixelString: string) {
`string`대신 템플릿 리터럴 타입쓰면 될 것 같은데..생각해보니 ts 버전이 낮아 안되겠네요..

2022-01-06 03:09 UTC, js87zz commented on packages/toast-ui.grid/src/view/editingLayer.tsx
> +  private initBodyScroll: InitBodyScroll = { initBodyScrollTop: 0, initBodyScrollLeft: 0 };
끝에 `Pos` suffix 붙여주는게 더 명확할 것 같습니다

2022-01-06 03:09 UTC, js87zz commented on packages/toast-ui.grid/src/view/editingLayer.tsx
> +    }
엔터키로 편집 종료하거나 탭키로 에디팅 레이어 이동할 때는 문제 없나요?

2022-01-07 04:50 UTC, jajugoguma commented on packages/toast-ui.grid/src/view/editingLayer.tsx
> +    }
키보드 동작이 정상적으로 동작하지 않아 원인을 알아보니, `visibility: hidden;`이나 `display: none;`처럼 DOM 상에 보여지지 않는 요소에는 포커스를 줄 수 없다는 것을 알았습니다.
실제로 에디팅 중에 스크롤을 이용해 에디터를 보이지 않게 설정하면 editingLayer`가 포커스를 잃는 것을 확인했습니다.

이를 해결하기 위해서는 에디터를 DOM 상에서 보이지만, 실제로는 보이지 않게 해야했습니다. 이를 위해 드롭다운 레이어의`top`과 `left`를 `0`으로 설정해 그리드 바디 좌측 상단에 위치하도록 하고 `z-index`를 `-100`을 할당해 그리드 셀 아래로 숨겨지도록 했습니다. 

결과적으로 보여지는 화면은 같지만, 키보드 동작은 정상적으로 수행할 수 있었습니다. 이런 방법을 이용해도 괜찮을까요?

2022-01-07 05:22 UTC, js87zz commented on packages/toast-ui.grid/src/view/editingLayer.tsx
> +    }
@jajugoguma 
stack context나 위치 자체를 바꾸기 보다 `opacity`로 제어하는게 제일 나을 것 같은데 어떤가요?

2022-01-07 05:43 UTC, jajugoguma commented on packages/toast-ui.grid/src/view/editingLayer.tsx
> +    }
처음에는 `opacity`를 이용해 제어했었습니다. 

![](https://user-images.githubusercontent.com/41339744/148497269-da083164-bdc4-4f2b-9d0c-bcd3e08907e4.gif)

그러나 드롭다운 레이어가 보이지만 않을 뿐 실제로를 그 위치 그대로 있어서 위 그림과 같이 드롭다운 내 요소가 선택되어 값이 변하는 것을 볼 수 있었습니다. 그래서 stack context를 이용해 드롭다운 레이어가 선택되지 않도록 하고, 보이지 않는다면 레이어의 위치를 계속 이동시킬 필요가 없다고 생각해서 `top: 0px; left: 0px;`에 고정시키는 방법을 사용해보았습니다.

2022-01-07 10:25 UTC, merged