fix: dynamic row span with scroll
nhn/tui.grid pull request #1606
Opened 2022-03-08 01:30 UTC by jajugoguma

### Please check if the PR fulfills these requirements
- [x] It's submitted to right branch according to our branching model
- [x] It's right issue type on title
- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [x] The commit message follows our guidelines
- [x] Tests for the changes have been added (for bug fixes/features)
- [ ] Docs have been added/updated (for bug fixes/features)
- [ ] It does not introduce a breaking change or has description for the breaking change

### Description

* Fixed row spans breaking when scrolling.
  * It is caused by observable data and row span attribute that will be depreacted.
    * For performance, the grid set lazy observable to array values like data.
    * Because of this, in initial, only data in viewport change to observable.
    * When scrolling, the data incoming to viewport changes to observable.
      * At this moment, rowSpanMap is set by rowSpan attribute(regardless It is already set).
      * But, dynamic row span implements without row span attribute. It only uses real data.
      * So, I fixed it to use rowSpanMap that was already set.
---
Thank you for your contribution to TOAST UI product. 🎉 😘 ✨

2022-03-10 03:34 UTC, adhrinae requested changes
`only` 부분 말고는 제가 더 리뷰해줄 부분이 없네요. 그래도 원인 파악하고 대책 고민하느라 고생했어요.

2022-03-10 03:34 UTC, adhrinae commented on packages/toast-ui.grid/cypress/integration/rowSpan.spec.ts
> +  cy.getByCls('rside-area', 'body-area').wait(100).scrollTo(position);
이미 어느정도 시도를 해 보고 썼을거라 생각하지만, 보통 명시적으로 `wait` 같은 API를 E2E 테스트에 쓰는건 Bad Practice로 알려져있어요. 혹시 문서의 이런 내용이 도움이 되진 않을까요?

https://docs.cypress.io/guides/references/best-practices#Unnecessary-wait-for-cy-get

2022-03-10 03:34 UTC, adhrinae commented on packages/toast-ui.grid/cypress/integration/rowSpan.spec.ts
> +  it.only('should render rowSpan cell properly when scroll', () => {
`only` 빼는걸 깜빡했군요.

기왕 이렇게 된거 린트 룰 적용하고, 가급적이면 pre-commit 훅 적용하는거 얼른 살펴봤음 좋겠네요.

2022-03-10 03:34 UTC, adhrinae commented on packages/toast-ui.grid/src/store/data.ts
> +  (row as Row).rowSpanMap = (row as Row).rowSpanMap ?? createRowSpanMap(row, rowSpan, prevRow);
`createRowSpanMap` 이 어떤 역할을 하는지 조금 더 설명이 있었으면 좋았겠어요.

2022-03-10 07:04 UTC, lja1018 approved these changes
리뷰 완료합니다.

2022-03-11 06:34 UTC, jajugoguma commented on packages/toast-ui.grid/src/store/data.ts
> +  (row as Row).rowSpanMap = (row as Row).rowSpanMap ?? createRowSpanMap(row, rowSpan, prevRow);
`createRowSpanMap`은 현재 row의`rowSpanMap`(실제로 사용할 row span 데이터)를 `_attributes`의 `rowspan`(데이터 주입 시 데이터의 속성으로 지정한 고정 row span 옵션 속성 값)과 앞선 row를 이용해 새롭게 계산 후 반환하는 함수 입니다. 

추후에는 조금 더 부가적인 설명을 작성하도록 하겠습니다.

2022-03-11 06:39 UTC, jajugoguma commented on packages/toast-ui.grid/cypress/integration/rowSpan.spec.ts
> +  cy.getByCls('rside-area', 'body-area').wait(100).scrollTo(position);
`wait`가 없으면 실제로 스크롤이 동작하지 않는 문제가 있습니다. 조금더 자세한 내용을 찾아보고 수정할 방안을 모색해보도록 하겠습니다.

2022-03-11 06:39 UTC, jajugoguma commented on packages/toast-ui.grid/cypress/integration/rowSpan.spec.ts
> +  it.only('should render rowSpan cell properly when scroll', () => {
린트 룰, pre-commit 훅 적용은 별도로 적용에 PR 올리도록 하겠습니다. 감사합니다!

2022-03-11 07:49 UTC, merged