Feat/remove rows
nhn/tui.grid pull request #1658
Opened 2022-04-28 08:25 UTC by jajugoguma

### Please check if the PR fulfills these requirements
- [x] It's submitted to right branch according to our branching model
- [x] It's right issue type on title
- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [x] The commit message follows our guidelines
- [x] Tests for the changes have been added (for bug fixes/features)
- [ ] Docs have been added/updated (for bug fixes/features)
- [ ] It does not introduce a breaking change or has description for the breaking change

### Description

* Added `removeRows` API to delete multiple rows at once.
  * If passed an array of `rowKeys`, delete all rows corresponding to each `rowKey`.
  * If there is no row corresponding to the given `rowKeys`, no action is taken.

---
Thank you for your contribution to TOAST UI product. 🎉 😘 ✨

2022-05-02 06:26 UTC, lja1018 reviewed
리뷰 완료합니다.

2022-05-02 06:26 UTC, lja1018 commented on packages/toast-ui.grid/src/query/data.ts
> +    rowIndexes: [],
복수형 `rowIndices`입니다.

2022-05-02 06:26 UTC, lja1018 commented on packages/toast-ui.grid/src/query/data.ts
> +      acc.nextRows.push(data.rawData[index + 1]);
`index + 1`이 `data.rawData`를 벗어나는 경우는 없을까요?

2022-05-02 06:31 UTC, adhrinae requested changes
특정 함수 이름을 다시 한번 확인해주세요.

그리고 이미 dispatch로 `removeRows` 액션은 있었던거같네요. 왜 커밋 안에는 포함되어있지 않은지 계속 찾았습니다.

2022-05-02 06:31 UTC, adhrinae commented on packages/toast-ui.grid/src/query/data.ts
> +export function getRowInfoList({ data }: Store, rowKeys: RowKey[]) {
함수의 목적 자체가 `RemoveTargetRows` 를 리턴하기 위한 것인데 이름은 범용적으로 되어있네요. 용도 구분을 명확하게 할 수 있는 이름이었으면 좋겠습니다.

2022-05-02 06:31 UTC, adhrinae commented on packages/toast-ui.grid/src/query/data.ts
> +  data.rawData.reduce((acc, row, index) => {
`rawData` 가 배열이 아니라 Map으로 되어있는게 제일 좋겠다 싶긴 한데... 그리고 직접 코드 들여다봤을 때는 `rawData` 의 타입이 any로 나오네요? VSCode 추론의 오류같긴 하지만요.

아마 `data` 가 훨씬 양이 많을테니 `rowKeys` 가 있는지 찾는 동작을 `rawData` 의 루프 안에서 한 것 같은데 로직의 전개 방향이 뒤집어졌다는 느낌이 들어서 처음에는 읽기 어려웠어요.

개인적으로는 `rawData` 를 `Map<rowKey, data>` 같은 타입으로 만든 다음 rowKeys 배열 돌면서 바로바로 해당 key가 있는지 확인하고 데이터를 꺼내오는 식으로 만들고 싶네요. 만약 그렇게 한다면 데이터 양에 따라 메모리 공간을 엄청 잡아먹을 것 같아서 하기 어려울 것 같지만요.

2022-05-02 09:31 UTC, jwlee1108 approved these changes
리뷰 완료합니다. 다른 분들 의견 참고 부탁드려요.

2022-05-02 09:31 UTC, jwlee1108 commented on packages/toast-ui.grid/src/query/data.ts
> +  data.rawData.reduce((acc, row, index) => {
Hashing용 Map을 만드는 건 항상 트레이드오프가 따라오는 것 같아요. 
추가로 그리드의 넥스트는 rawData 구조를 없애는거라 그때 고민을 좀 해보면 좋겠습니다.

2022-05-04 08:44 UTC, jajugoguma commented on packages/toast-ui.grid/src/query/data.ts
> +      acc.nextRows.push(data.rawData[index + 1]);
넘어가게 되는 경우 `undefined`를 반환하고 그에 따라 처리하도록 되어있습니다!

2022-05-04 08:54 UTC, merged