fix: paste more rows than rows of the grid (fix #1635)
nhn/tui.grid pull request #1685
Opened 2022-05-26 05:48 UTC by jajugoguma

### Please check if the PR fulfills these requirements
- [x] It's submitted to right branch according to our branching model
- [x] It's right issue type on title
- [x] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [x] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes/features)
- [ ] Docs have been added/updated (for bug fixes/features)
- [ ] It does not introduce a breaking change or has description for the breaking change

### Description

* Fixed an issue where data was truncated when pasting more rows than the number of rows in the grid.
  * When calculating the range to be pasted during paste, if it exceeds the row range of the current grid, it adds as many blank rows as it exceeds and then performs pasting.
* The test could not be added due to a [Clipboard issue in Cypress](https://github.com/cypress-io/cypress/issues/2386).

**As-Is**

![](https://user-images.githubusercontent.com/41339744/170424671-db5627b3-14a0-450a-a4d6-8ff6503d1c3b.gif)

**To-Be**

![](https://user-images.githubusercontent.com/41339744/170424813-bb7dffd0-fbae-4450-b958-442fb4614977.gif)

---
Thank you for your contribution to TOAST UI product. 🎉 😘 ✨

2022-05-26 23:48 UTC, adhrinae requested changes
리뷰 완료합니다.

2022-05-26 23:48 UTC, adhrinae commented on packages/toast-ui.grid/src/query/clipboard.ts
> +  }
저번 PR에 언급했던거랑 비슷하지만, 이 쿼리라는 모듈 영역에서 할 동작은 아닌거같아요.

- 쿼리라는 이름의 특성 상 순수 함수이면 충분할 것 같은데 사이드 이펙트를 일으키고 있어요.
- 디스패쳐가 쿼리를 의존하고, 쿼리가 디스패쳐를 의존하는 그닥 좋지 않은 의존 관계를 형성했어요. 가급적이면 의존성은 한 방향으로 흐르도록 만들어봅시다.

[paste](https://github.com/nhn/tui.grid/blob/4e01eea5768206992b322cf8a0b2192342fc783f/packages/toast-ui.grid/src/dispatch/keyboard.ts#L232) 함수에서 쿼리를 호출하고 있는데, 사전에 길이의 차이가 있는지 확인하고 Row를 늘려주는 동작은 여기서 수행한 뒤에 `getRangeToPaste` 를 호출해도 충분할 것 같아요.

2022-05-27 06:44 UTC, lja1018 reviewed
리뷰 완료합니다.

2022-05-27 08:26 UTC, adhrinae approved these changes

2022-05-27 08:27 UTC, merged