fix: cross site script vulnerability (fix #1669)
nhn/tui.grid pull request #1741
Opened 2022-07-12 07:23 UTC by jajugoguma

### Please check if the PR fulfills these requirements
- [x] It's submitted to right branch according to our branching model
- [x] It's right issue type on title
- [x] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [x] The commit message follows our guidelines
- [x] Tests for the changes have been added (for bug fixes/features)
- [ ] Docs have been added/updated (for bug fixes/features)
- [ ] It does not introduce a breaking change or has description for the breaking change

### Description

related issue: #1669 

* Fixed an issue that the XSS vulnerability by using DOMPurify.

---
Thank you for your contribution to TOAST UI product. 🎉 😘 ✨

2022-07-13 00:12 UTC, adhrinae requested changes

2022-07-13 00:12 UTC, adhrinae commented on packages/toast-ui.grid/cypress/integration/renderer.spec.ts
> +it('should render data to plain text in default renderer', () => {
테스트가 XSS 방어를 위한 것으로 안보여요.

그리고 이 경우 **'얼럿이 실행되지 않았다'** 를 테스트해야하는데 Cypress에는 얼럿에 이벤트 리스너를 달 수 있는 기능이 있으니까 이걸 활용하는게 좋겠어요.

```js
cy.on('window:alert', (alertMessage) => {
  // 이 콜백이 실행되지 않았음을 테스트한다.
});
```

2022-07-13 00:12 UTC, adhrinae commented on packages/toast-ui.grid/cypress/integration/renderer.spec.ts
> +it('should render data to plain text in default renderer', () => {
추가로 XSS 방어를 테스트하려면 HTML 스트링이 들어왔을 때 문제가 되는 문자열이 제거되었는지 등을 테스트하면 좋은데, 다른 예를 조금 더 찾아보면 좋겠다는 생각이 드네요.

2022-07-14 07:02 UTC, lja1018 reviewed
리뷰 완료합니다.

2022-07-14 07:02 UTC, lja1018 commented on packages/toast-ui.grid/package.json
> +    "dompurify": "^2.3.9",
종속성이 추가됬다고 문서에 추가하지 않아도 될까요?

2022-07-15 01:12 UTC, jajugoguma commented on packages/toast-ui.grid/cypress/integration/renderer.spec.ts
> +it('should render data to plain text in default renderer', () => {
앞서 말씀해주신 방법으로 테스트를 해보려했으나 `alert`이 항상 테스트가 종료된 이후에 무한히 호출되는 문제가 있어서 문제가 되는 문자열이 제거되었는지 확인 하는 테스트로 변경했습니다.

2022-07-15 01:18 UTC, adhrinae approved these changes

2022-07-15 01:54 UTC, merged