feat: custom header by passing html element
nhn/tui.grid pull request #1955
Opened 2023-08-25 02:26 UTC by jajugoguma

### Please check if the PR fulfills these requirements
- [x] It's submitted to right branch according to our branching model
- [x] It's right issue type on title
- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [x] The commit message follows our guidelines
- [x] Tests for the changes have been added (for bug fixes/features)
- [x] Docs have been added/updated (for bug fixes/features)
- [x] It does not introduce a breaking change or has description for the breaking change

### Description

* Added custom header functionality.
  * You can set a variety of HTML elements in the header, including images, icons, and more.

**To-Be**

<img width="307" alt="image" src="https://github.com/nhn/tui.grid/assets/41339744/410c41e3-5926-4b47-baf5-388f447a5f1e">

---
Thank you for your contribution to TOAST UI product. 🎉 😘 ✨

2023-08-27 16:27 UTC, jwlee1108 requested changes
리뷰 완료합니다.

2023-08-27 16:27 UTC, jwlee1108 commented on packages/toast-ui.grid/src/view/headerCheckbox.tsx
> +        dangerouslySetInnerHTML={{ __html: `${this.props.header}_123123` }}
123123이 들어가는 게 맞는건가요?

2023-08-28 01:21 UTC, jwlee1108 approved these changes

2023-08-28 01:27 UTC, sunyoungBae approved these changes

2023-08-28 01:35 UTC, dotaitch approved these changes

2023-08-28 01:35 UTC, dotaitch commented on packages/toast-ui.grid/src/store/column.ts
>  } from '@t/options';
P5: grid의 eslint에는 sort-imports 규칙이 없는데 import가 파일마다 변경되어 있네요. 개인 설정에 이 규칙이 적용되어 있는건지 확인 부탁드려요.
원래 sort-imports 규칙이 없다보니 다른 파일도 전부 import가 정렬되어 있지 않아서 확인하는 파일마다 전부 변경사항이 생길텐데, 사실 이건 PR과 무관한 변경사항이라서요. 만약 sort-imports를 적용하는게 좋을 것 같다면 PR 새로 만들어서 한번에 전부 변경하도록 하면 좋을 것 같습니다.

2023-08-28 01:46 UTC, jajugoguma commented on packages/toast-ui.grid/src/store/column.ts
>  } from '@t/options';
intellij에 설정되어 있어서 변경되었나 보네요... 이건 추후에 한번에 변경하도록 하겠습니다 ㅎㅎ

2023-08-28 01:54 UTC, merged